In [17]:
import pandas as pd

iem=pd.read_csv('data/iem_info_20210902.csv')

In [18]:
iem_tp=iem.loc[:1078]

In [19]:
iem_tp

       iem_cd iem_krl_nm  btp_cfc_cd  mkt_pr_tal_scl_tp_cd  stk_dit_cd
0     A000020       동화약품           8                     2          99
1     A000080      하이트진로          14                     2           1
2     A000180     성창기업지주           5                     3          99
3     A000227    유유제약2우B           8                    99          99
4     A000325     노루홀딩스우           2                    99          99
...       ...        ...         ...                   ...         ...
1074  A064820        케이프          10                     3          99
1075  A064850     에프앤가이드           5                     3          99
1076  A065150       엠피대산           7                     3          99
1077  A065170      넥스트BT           7                     3          99
1078  A065370      위세아이텍          10                     3          99

[1079 rows x 5 columns]

In [49]:
from tqdm import tqdm
from selenium import webdriver
import time

In [ ]:

chromedriver = 'C:/Users/chaeh/chromedriver.exe'
driver = webdriver.Chrome(chromedriver)


for i in tqdm(range(len(iem_tp))):
   
    driver.get('https://datalab.naver.com/keyword/trendSearch.naver')
    name=iem_tp['iem_krl_nm'][i]
    search_iem = driver.find_element_by_id("item_keyword1")
    search_iem.send_keys(name)
    driver.find_element_by_xpath('//*[@id="startYear"]').click()
    driver.find_element_by_xpath('//*[@id="startYearDiv"]/ul/li[1]/a').click()
    driver.find_element_by_xpath('//*[@id="startMonth"]').click()
    driver.find_element_by_xpath('//*[@id="startMonthDiv"]/ul/li[1]/a').click()
    driver.find_element_by_xpath('//*[@id="startDay"]').click()
    driver.find_element_by_xpath('//*[@id="startDayDiv"]/ul/li[1]/a').click()

    driver.find_element_by_xpath('//*[@id="endMonth"]').click()
    driver.find_element_by_xpath('//*[@id="endMonthDiv"]/ul/li[1]/a').click()
    driver.find_element_by_xpath('//*[@id="endDay"]').click()
    driver.find_element_by_xpath('//*[@id="endDayDiv"]/ul/li[1]/a').click()

    driver.find_element_by_xpath('//*[@id="content"]/div/div[2]/div[1]/div/form/fieldset/a').click()
    
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/div[1]/div/div/div/div/div/div[1]/div[4]/a').click()
    #driver.close()

  0%|▏                                                                              | 3/1079 [00:10<1:01:11,  3.41s/it]